#pragma once

enum class CommandType : char8_t
{
	COMMAND_BATCH,
	POSITION_CHANGE,
	TANK_SHOT,
	HEALTH_CHANGE,
	DISPOSE,
	STATISTICS_CHANGE,
	KEY_STATE_CHANGE,
	GAME_STATE_CHANGE,
	FORTRESS_CHANGE,
	BONUS_SPAWN,
	BONUS_DESPAWN,
	BONUS_STATUS,
	RESPAWN_TANK,
	OBSTACLE_SPAWN,
	TANK_SPAWN_COMPLETE,
	SIGNAL_EVENT,
	DISCONNECT
};
